services:
  remix-app:
    container_name: 3df
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    network_mode: 'host'
    volumes:
      - ./.env:/app/.env
