name: deploy 3DF/main
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: build & deploy
    runs-on: self-hosted

    steps:
      - name: checkout latest 
        uses: actions/checkout@v4

      - name: copy .env
        run: cp ${{ secrets.ENV_FILE_PATH }} .
          
      - name: install dependencies
        run: npm install
        
      - name: build app
        run: npm run build
      
      - name: start application
        run: | 
          pkill -f "remix-serve" || true
        
          nohup npm run start > app.log 2>&1 &

          sleep 3
        