name: deploy 3DF/main
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: build & deploy
    runs-on: self-hosted

    steps:
      - name: checkout latest 
        uses: actions/checkout@v4

      - name: copy .env
        run: cp ${{ secrets.ENV_FILE_PATH }} .
          
      - name: install dependencies
        run: |
          npm install

          /usr/bin/npm install -g pm2 || true
        
      - name: build app
        run: npm run build
      
      - name: start application
        run: | 
          pm2 delete 3df || true
        
          pm2 start "npm run start" --name "3df"

          pm2 save

          sleep 3
        