name: deploy 3DF/main
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: build & deploy
    runs-on: self-hosted

    steps:
      - name: checkout latest 
        uses: actions/checkout@v4

      - name: copy .env
        run: cp ${{ secrets.ENV_FILE_PATH }} .
          
      - name: deploy with docker-compose
        run: |
          docker-compose down || true
          
          docker-compose up -d --build
          
          docker image prune -f