name: deploy 3DF/main
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: build app
    runs-on: self-hosted

    steps:
      - name: checkout latest code
        uses: actions/checkout@v4
          
      - name: install dependencies
        run: npm install
        
      - name: build app
        run: npm run build

      - name: remove and initialize new app folder
        run: |
          rm -rf /home/wilbir/3DF/main
          
          mkdir -p /home/wilbir/3DF/main
        
      - name: deploy to 3DF folder
        run: |
          cp -R build/* /home/wilbir/3DF/main
          
          chmod -R 755 /home/wilbir/3DF/main
          
          echo "deployment complete"
      
      - name: start application
        run: |
          npx remix-serve /home/wilbir/3DF/main/server/index.js
          
          echo "application started"